name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      - name: Verify dependencies
        run: |
          go mod download
          go mod Verify
      
      - name: Build
        run: go build -v -o bin/bmstu_rsoi_lab1 .

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: bmstu_rsoi_lab1_binary
          path: bin/bmstu_rsoi_lab1

  unit-test:
    name: Unit Testing
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run unit tests
        run: go test -v -short ./internal/services/...


  # build:
  #   name: Autograding
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     # TODO build, test and deploy project

  #     - name: Run API Tests
  #       uses: matt-ball/newman-action@master
  #       with:
  #         collection: postman/[inst] Lab1.postman_collection.json
  #         environment: postman/[inst][heroku] Lab1.postman_environment.json
  #         delayRequest: 100
  #         reporters: '[ "cli" ]'

  #     - name: Autograding
  #       uses: education/autograding@v1
  #       continue-on-error: true

  #     - name: Github auto grader mark
  #       uses: Romanow/google-sheet-autograder-marker@v1.0
  #       with:
  #         google_token: ${{secrets.GOOGLE_API_KEY}}
  #         sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
  #         homework_number: 1
  #         user_column: 'D'
  #         column_offset: 'F'
  #         mark: "'+"